#!/usr/bin/env bash

export PATH=/opt/tcc/bin:$PATH
#E='valgrind --leak-check=full --quiet'
E=

comp=$3
if [ -z $comp ]; then
    comp=clang
fi

echo ------

#$E ./sregex -g --thompson --thompson-jit --pike "$1" $2
#$E ./sregex -g --pike "$1" $2

#$E ./pcre -g --default --jit --dfa "$1" $2
$E ./pcre -g --default --jit "$1" $2

#$E ./pcre2 --repeat=1000000 -g --default "$1" $2
#$E ./pcre2 --repeat=1000000 -g --jit "$1" $2
$E ./pcre2 -g --default --jit "$1" $2
$E ./hyperscan -g --repeat=5 "$1" $2
$E ./re2 --repeat=5 -g "$1" $2
#$E ./re2 --repeat=100000 -g "$1" $2

echo ------
