#!/usr/bin/env bash

export PATH=/opt/tcc/bin:$PATH
#E='valgrind --leak-check=full --quiet'
E=

echo ------

#$E ./sregex --thompson --thompson-jit --pike "$1" $2
#$E ./sregex --pike "$1" $2

#$E ./pcre -g --default --jit --dfa "$1" $2
$E ./pcre -g --default --jit "$1" $2

#$E ./pcre2 --repeat=1000000 -g --default --jit "$1" $2
$E ./pcre2 -g --default --jit "$1" $2

$E ./re2 --repeat=1 -g "$1" $2
#$E ./re2 --repeat=100000 -g "$1" $2

exefile=./dfa3.out
if [ ! -f $exefile ]; then
    ../re.pl --debug=0 --repeat=5 -g --timer --cc="gcc -O3" -o $exefile "$1" a > /dev/null || exit 1
fi
$exefile < $2

exefile2=./dfa3-g.out
#../re.pl --debug=0 --repeat=100000000 -g --cc="gcc -g -O3" -o $exefile2 "$1" a > /dev/null || exit 1
#$exefile2 < $2

#./re1 --thompson --pike "$1" $2

echo ------
